spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/TestcodeApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create # ddl-auto 같은 경우 실행 환경마다 신경써서 작성할 것.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # 서버 실행시 매번 data를 생성해 내어야 하는데, data.sql을 실행
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      format_sql: true
  sql:
    init:
      mode: never
